sudo: false
language: node_js

cache: npm

node_js:
  - '10'

services:
  - docker

before_install:
  - docker build -t loopback .
  - docker run -p 127.0.0.1:80:4567 -d loopback:latest
  - docker ps -a
  - docker tag loopback:latest mohamedragabessa/vehicle-frontend:latest

# before_install:
#   - pip install --user awscli
#   - export PATH=$PATH:$HOME/.local/bin
#   - eval $(aws ecr get-login --no-include-email --region us-east-2)
#   - docker build -t vehicles/frontend .
#   - docker run -p 127.0.0.1:80:4567 -d vehicles/frontend:latest
#   - docker tag vehicles/frontend:latest 307045200927.dkr.ecr.us-east-2.amazonaws.com/vehicles/frontend:latest

# script: npm run test
install: npm install

branches:
  only:
    - master

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push mohamedragabessa/vehicle-frontend:latest

deploy:
  provider: script
  script: echo "Applcation simulation!"

# deploy:
#   provider: elasticbeanstalk
#   access_key_id:
#     secure: '$ACCESSKEYID'
#   secret_access_key:
#     secure: '$SECRETACCESSKEY'
#   region: '$REGION'
#   app: 'vehicles-front-end'
#   env: 'vehicles-front-end-dev'
#   bucket_path: 'vehicles-front-end'
#   bucket_name: 'elasticbeanstalk-us-east-2-307045200927'
#   skip_cleanup: true
#   on:
#     branch: master

after_deploy:
  - echo "Applcation Deployed!"
