sudo: false
language: node_js

cache: npm

node_js:
  - '10'

services:
  - docker

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region us-east-2)
  - docker build -t vehicles/frontend .
  - docker run -p 127.0.0.1:80:4567 -d vehicles/frontend:latest
  - docker tag vehicles/frontend:latest 307045200927.dkr.ecr.us-east-2.amazonaws.com/vehicles/frontend:latest

# script: npm run test
# install: npm install

# branches:
#   only:
#     - master

before_deploy:
deploy:
  provider: script
  script: docker push 307045200927.dkr.ecr.us-east-2.amazonaws.com/vehicles/frontend:latest
  on:
    branch: master
